# Generated by Django 4.2.5 on 2023-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('price', models.IntegerField()),
                ('time', models.TimeField()),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
