# Generated by Django 4.2.2 on 2023-11-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='time',
        ),
        migrations.AddField(
            model_name='offers',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
