# Generated by Django 4.2.2 on 2023-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_offers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='uploads')),
                ('PhoneNumber', models.IntegerField(max_length=15)),
            ],
        ),
    ]
