# Generated by Django 4.2.2 on 2023-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='PhoneNumber',
            field=models.IntegerField(),
        ),
    ]
