# Generated by Django 5.0.2 on 2024-06-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_enquirys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactEquiry',
            new_name='ContactEnquiry',
        ),
    ]
