# Generated by Django 5.0.2 on 2024-06-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_enquirys', '0002_rename_contactequiry_contactenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
