# Generated by Django 5.0.2 on 2024-06-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_enquirys', '0003_alter_review_review'),
        ('services', '0005_alter_employee_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='services',
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.offers'),
            preserve_default=False,
        ),
    ]
